### ISSUE TITLE
Adding okta group to  existing app through TF

### ISSUE THREAD

**Issue by ashrith1357** [articulate/terraform-provider-okta#102]
Hello,

  Any help is appreciated. We were able to create okta groups ( Ex: aws_12345_ROrole ) but how to add this group to existing app in okta through this provider ?   when we try to use snippet of below code using okta_saml_app, this is trying to a new app rather adding the group. I don't want to create a saml app through so is there any other way to accomplish ?

resource "okta_group" "testgroup" {
  name = "testgroup"
}

resource "okta_saml_app" "testapp" {
  preconfigured_app = "amazon_aws"
  label             = "testapp"
--
groups = ["${okta_group.testgroup.id}"]

}

**Comment by quantumew** [comment]
Currently the way to do this is import your existing App and then simply add the group to the config. The caveat with this is you need to configure it to match your existing app before you do a `terraform apply`. This can be done by running a `terraform plan` and updating the config based on the diff.

Alternatively, I can see why you wouldn't want to manage your SAML app via TF, since Okta doesn't allow you to configure everything via the API. I could add a resource such as `okta_group_application_assignment` and a data resource for applications (already on the docket). It would look like this if I were to add these pieces:

```
data "okta_app" "test" {
    label = "my app label"
}

resource "okta_group" "test" {
    name = "test"
}

resource "okta_app_assignments" "test" {
   app_id = "${data.okta_app.test.id}"
   groups = ["${okta_group.test.id}"]
   users = [...]
}
```

Group/User App assignments are technically a separate API resource so I think this approach is acceptable and provides more flexibility.

**Comment by ashrith1357** [comment]
Thank you for the update and prompt reply. i really looking for resource (okta_app_assignments ) and data(okta_app) which you outlined above. i need to add groups over period of times and multiple times so don't want to create app each time when the new group comes up which need the app.

**Comment by quantumew** [comment]
Not sure I follow. This is what Terraform state is for. If you add groups over time to that app resource, it will not keep creating new applications, it will read in the true downstream resource, reconcile it with your config, then output a plan when you run `terraform plan`. Subsequently when you run `terraform apply` it will attempt to update your app resource, then if it is successful it will update your terraform state.
