### ISSUE TITLE
Deactivating User Fails

### ISSUE THREAD

**Issue by msmall-cotm** [articulate/terraform-provider-okta#104]
When attempting to deactivate a user by setting `status = "DEPROVISIONED"`, I receive the following error:

```
okta_user.ops: Modifying... (ID: 00u9acfthAZQrDvaG356)
  status: "PROVISIONED" => "DEPROVISIONED"

Error: Error applying plan:

1 error(s) occurred:

* okta_user.ops: 1 error(s) occurred:

* okta_user.ops: [ERROR] Cannot update a DEPROVISIONED user
```
The user is successfully deactivated, but the error message is misleading.

**Comment by quantumew** [comment]
The update function for this resource is flawed. It updates status first so that if you reactivate a user it updates their profile after but if you are updating it to `DEPROVISIONED` it still attempt to hit that code which predictably ends in an error. 
https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_user.go#L309-L318

What I am wonder is why we cannot update a deprovisioned user? If we can update a deprovisioned user we will just remove that guard. If not, we should be ordering the profile updates accordingly.

Thanks for reporting!
