### ISSUE TITLE
What does %[1] mean in the examples?

### ISSUE THREAD

**Issue by jpf** [articulate/terraform-provider-okta#117]
I'm new to Terraform, so please excuse my ignorance here. I've been looking through the examples and keep seeing `%[1]` – what does this do? I've scoured the Terraform documentation and haven't been able to find what this does.

**Comment by quantumew** [comment]
Due to time constraints we have not been able to stand up a wiki website like other providers (Terraform manually writes these, they don't have a generator). I decided to start using acceptance test fixtures that can serve as examples instead, so you are forced to document a resource/data source as you build it. This requires me to use string formatting to inject the random characters necessary to avoid resource collision. In Go using `%[1]d` means grab the first format arg, convert it from an int to a string, and place it there.

It occurred to me that I could hide this formatting a bit more. Potentially something a regex can find and replace that is plain text. I will leave this issue open to look into doing that instead or if I get around to standing up a wiki.

Docs about this:
https://github.com/articulate/terraform-provider-okta/tree/master/examples#test-fixture-examples

Wiki example
https://www.terraform.io/docs/providers/aws/index.html

Fixtures code
https://github.com/articulate/terraform-provider-okta/blob/master/okta/fixtures.go
https://github.com/articulate/terraform-provider-okta/blob/master/okta/data_source_auth_server_test.go#L13
