### ISSUE TITLE
Locked accounts cannot be unlocked

### ISSUE THREAD

**Issue by c-knowles** [articulate/terraform-provider-okta#225]
## Expected Behavior

If a user gets locked out then a terraform plan produces this:
```
  ~ okta_user.some_user
      status:           "LOCKED_OUT" => "ACTIVE"
```

Activating the user should be possible.

## Actual Behavior

If a user is locked out but active in the terraform config and then the above plan is applied, the following occurs:

```
Error: Error applying plan:

1 error occurred:
	* okta_user.some_user: 1 error occurred:
	* okta_user.some_user: [ERROR] Error Updating Status for User: The API returned an error: Activation failed because the user is already active
```

## Steps to Reproduce the Problem

1. Have an active user in the terraform code
2. Lock that user out, e.g. too many incorrect password entries
3. Try to plan and apply

**Comment by quantumew** [comment]
There is an unlock endpoint. Right now it is trying to call activate, which results in the error.

**Comment by c-knowles** [comment]
Awesome! Not tested yet but thanks for the quick response.

**Comment by shantanugadgil** [comment]
Let me chime in on the turn around speed ... since I have started using this provider (not knowing if it would help me solve my problems), I can wholeheartedly say that the enhancements have been indeed very quick, and have helped me to solve a real world problem very efficiently.

This project is on my watch list, as I want to know what new is going on; more than once I have found out capabilities of Okta due to this provider's examples! :smile:
