### ISSUE TITLE
To be able to create tokens under security->API

### ISSUE THREAD

**Issue by msmrnv1** [articulate/terraform-provider-okta#240]
I would like to be able to create a token that can be used later by an application to call Okta admin APIs. Is there a way to do it today?

End Point: api/internal/tokens?expand=user
Request Param: {"name":"Test Token"}

**Comment by quantumew** [comment]
There was a public API for this at one time but it was deprecated. We have recently considered starting to look at internal APIs for resources: #235. I fear this endpoint will be difficult to build a resource around. Tokens are tied to user accounts, this endpoint likely requires the user creating a token have an active session. I would guess this would require the provider to have each user's  creds in order to create their tokens. This is doable but I would imagine this would be very hard to support as a resource.

Either way I will look into this and either open a feature request with Okta, or create a resource for this.

**Comment by msmrnv1** [comment]
Ok, appreciated.. OKTA support did mention that they might release a feature to support the service accounts for token generation. I am not sure about the timing of that though.

**Comment by quantumew** [comment]
I do remember hearing about that, I will keep that in mind and report back. Thanks for the reminder!

**Comment by jeremie0** [comment]
I bet they are talking about the Oauth 2.0 for Okta APIs feature.

OAuth 2.0 for Okta APIs
Enable scoped OAuth 2.0 tokens for Okta APIs. This will allow administrators to configure specific scoped Okta API access policies for OAuth 2.0 and OIDC applications in an Okta tenant.

This will likely change the whole flow for interacting w/the Okta APIs.
