### ISSUE TITLE
Read existing config of Okta Org into terraform

### ISSUE THREAD

**Issue by Govvy** [articulate/terraform-provider-okta#276]
A way to read the current configuration of an okta tenant into terraform.

Provide a way to read back all the current config as a first step

That way anyone getting started with the CI/CD tooling can preserve any existing config in the environment and run these automated processes from then onwards…

**Comment by quantumew** [comment]
This would be outside the responsibility of the Terraform provider and instead would require a separate open source tool. One prominent example is the [AWS provider](https://github.com/terraform-providers/terraform-provider-aws) and the [tool used to aid in the import process]( https://github.com/dtan4/terraforming). All Terraform providers expose an [import command](https://www.terraform.io/docs/import/index.html) for each resource, which builds out Terraform state against existing infrastructure. 

With that said a tool such as this for Okta would be extremely useful for brownfield scenarios such as these. In the past I have written some script to make this process easier. They basically queried an API, took the JSON response and directly transformed it to HCL, wrote the config, then spit out a generated script which imports the resources when run. The only manual process is grooming the HCL. This sped up the process a bit but a tool that can do this but also get the mappings from JSON to HCL right would be wonderful. At some point I would like to start such a project.

**Comment by quantumew** [comment]
Ok closing this here since the work is not directly related to this repo. One of these weekends, likely after finishing up the Hashicorp review, I will get to work on this https://github.com/quantumew/terraforming-okta. It will be a cli you point at your tenant, it will have JSON to HCL mappings, and it will generate the config. It likely will also spit out a JSON file mapping addresses to IDs with a subcommand that runs import against those. Could be a fun project, glad to take any assistance if anyone wants to get their Golang on.

**Comment by jralmaraz** [comment]
Hi @quantumew , keen to help with this one !

**Comment by quantumew** [comment]
Hey @Govvy, this is the one I have always used https://github.com/kvz/json2hcl

**Comment by quantumew** [comment]
Also here some discussion on the matter https://github.com/hashicorp/hcl/issues/294
