### ISSUE TITLE
Email Template customization

### ISSUE THREAD

**Issue by msmrnv1** [articulate/terraform-provider-okta#286]
Hi,

I am trying to customize the email templates and I would like to reuse the existing HTML templates that I have. It is a pretty long html text. What would be the best approach to do that?

Also, I would like to customize the sender from. Can this be done thru terraform?

**Comment by quantumew** [comment]
Unfortunately, last I checked the sender was set via the customization settings which doesn't have an exposed API. I can verify that though. 

As to writing the template in Terraform, I am guessing you are having trouble because we don't do any normalization, which makes the template in TF not very readable since the API likely normalizes it and ends up in a perpetual diff. Let me write a more complex example and add a `StateFunc` to do some normalization so you can write a more readable template.

Schema ref: https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_okta_template_email.go#L18-L21.

**Comment by quantumew** [comment]
In the meantime you can use this example to guide you https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_template_email/basic.tf. It might require you to write your template in an editor, then normalize it yourself until I automate that!

**Comment by msmrnv1** [comment]
Yes, you're right on point. Thanks
