### ISSUE TITLE
Password policy - allow setting userLockoutNotificationChannels

### ISSUE THREAD

**Issue by jeremie0** [articulate/terraform-provider-okta#328]
**Is your feature request related to a problem? Please describe.**
The Okta UI allows us to enable "Send lockout email to user".
In the API for password policies,  it looks like this is undocumented, but is set via:
```
"settings": {
   "password": {
      "lockout": {
          "userLockoutNotificationChannels": [
               "EMAIL"
           ]
```

can the terraform provider also let us set this?

**Describe the solution you'd like**
option for ```okta_policy_password```  to ```send_lockout_email = true```

**Comment by jralmaraz** [comment]
The payload to {{url}}/api/v1/policies needs to go like this:

```
...{before}
            "lockout": {
                "maxAttempts": 10,
                "autoUnlockMinutes": 60,
                "showLockoutFailures": true,
                "userLockoutNotificationChannels": ["EMAIL"]
              
            }
...{after}
```

I wanted to use schema.TypeBool in the schema to allow the suggestion from @jeremie0 to something like "send_lockout_email = true". Due to my coding limitation, I didn't know the best approach to map string{"[\"EMAIL\"]"} to a boolean attribute, so I commited for revew with a schema.TypeString for now (also needed to add UserLockoutNotificationChannels to "template.Settings.Password.Lockout." and "policy.Settings.Password.Lockout.UserLockoutNotificationChannels").

**Comment by quantumew** [comment]
Hey @jralmaraz , thanks for taking a look at this! I am personally slightly more partial to this being a Set of strings rather than a boolean that does magic. That way when Okta adds new notification channels, it just works, theoretically. Although I could be persuaded, the boolean is definitely nice and easy. 

With that said here is an example of a Set of strings https://github.com/articulate/terraform-provider-okta/blob/master/okta/resource_okta_group_roles.go#L30-L35. 

As for the boolean approach here is some pseudo code

```
const email = "EMAIL"

if d.Get("send_lockout_email").(bool) {
    policy.Settings.Password.Lockout.UserLockoutNotificationChannels = []string{email}
}
```

Glad to 👁 a PR if you got one!

**Comment by jralmaraz** [comment]
Hi @quantumew , sorry, I was offline for 4 days for a trip, will look at your suggestion and put the PR in place as soon as I can, cheers!

**Comment by quantumew** [comment]
@jralmaraz no worries! Thanks for your contribution!!

**Comment by jralmaraz** [comment]
@quantumew as I know there's some work going on to improve/change the SDK's extension, let me know if the PR I added for the Lockout is OK or if that should be changed. Thanks!
