### ISSUE TITLE
Group Rules | New Resource

### ISSUE THREAD

**Issue by robwaldron-flg** [articulate/terraform-provider-okta#87]
Now that we have both Group and User resources; it'd be great if we could get one called "group_rule" so that we have the ability to define rules and users are added dynamically based on profile attributes.

**Comment by quantumew** [comment]
Good call. Will drop this in the appropriate project. For reference: https://developer.okta.com/docs/api/resources/groups#group-rule-operations

**Comment by robwaldron-flg** [comment]
@quantumew - I'm very new to golang (though been using terraform for a good while now). I'd be keen to take a crack at adding this resource if it's not being picked up for a while, and then work through any comments to fix?

**Comment by quantumew** [comment]
@robwaldron-flg that would be great. We are always open to contributions. Let me know if you have any questions on setting up a free Okta account in order to run the acceptance tests. I will ammend the README so it has more info on this. The only other caveat is we are using two SDKs due to the official SDK not supporting some resources so clients for both are available in the metadata and there are helper functions in utils to extract them. Thanks!
